// Code generated by MockGen. DO NOT EDIT.
// Source: lookup_log.go
//
// Generated by this command:
//
//	mockgen -source=lookup_log.go -destination=../mock/repository/lookup_log_mock.go -package=mockrepository
//

// Package mockrepository is a generated GoMock package.
package mockrepository

import (
	context "context"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockLookupLogRepository is a mock of LookupLogRepository interface.
type MockLookupLogRepository struct {
	ctrl     *gomock.Controller
	recorder *MockLookupLogRepositoryMockRecorder
	isgomock struct{}
}

// MockLookupLogRepositoryMockRecorder is the mock recorder for MockLookupLogRepository.
type MockLookupLogRepositoryMockRecorder struct {
	mock *MockLookupLogRepository
}

// NewMockLookupLogRepository creates a new mock instance.
func NewMockLookupLogRepository(ctrl *gomock.Controller) *MockLookupLogRepository {
	mock := &MockLookupLogRepository{ctrl: ctrl}
	mock.recorder = &MockLookupLogRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLookupLogRepository) EXPECT() *MockLookupLogRepositoryMockRecorder {
	return m.recorder
}

// LogLookup mocks base method.
func (m *MockLookupLogRepository) LogLookup(ctx context.Context, name string, fetchedAt time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogLookup", ctx, name, fetchedAt)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogLookup indicates an expected call of LogLookup.
func (mr *MockLookupLogRepositoryMockRecorder) LogLookup(ctx, name, fetchedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogLookup", reflect.TypeOf((*MockLookupLogRepository)(nil).LogLookup), ctx, name, fetchedAt)
}
