// Code generated by MockGen. DO NOT EDIT.
// Source: pokemon_cache.go
//
// Generated by this command:
//
//	mockgen -source=pokemon_cache.go -destination=../mock/cache/pokemon_cache_mock.go -package=mockcache
//

// Package mockcache is a generated GoMock package.
package mockcache

import (
	context "context"
	pokeapi "pokemon-cache-service/internal/pokeapi"
	reflect "reflect"
	time "time"

	gomock "go.uber.org/mock/gomock"
)

// MockPokemonCache is a mock of PokemonCache interface.
type MockPokemonCache struct {
	ctrl     *gomock.Controller
	recorder *MockPokemonCacheMockRecorder
	isgomock struct{}
}

// MockPokemonCacheMockRecorder is the mock recorder for MockPokemonCache.
type MockPokemonCacheMockRecorder struct {
	mock *MockPokemonCache
}

// NewMockPokemonCache creates a new mock instance.
func NewMockPokemonCache(ctrl *gomock.Controller) *MockPokemonCache {
	mock := &MockPokemonCache{ctrl: ctrl}
	mock.recorder = &MockPokemonCacheMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPokemonCache) EXPECT() *MockPokemonCacheMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockPokemonCache) Get(ctx context.Context, name string) (*pokeapi.PokemonData, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, name)
	ret0, _ := ret[0].(*pokeapi.PokemonData)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockPokemonCacheMockRecorder) Get(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockPokemonCache)(nil).Get), ctx, name)
}

// Set mocks base method.
func (m *MockPokemonCache) Set(ctx context.Context, name string, data *pokeapi.PokemonData, ttl time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, name, data, ttl)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockPokemonCacheMockRecorder) Set(ctx, name, data, ttl any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockPokemonCache)(nil).Set), ctx, name, data, ttl)
}
