// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=../mock/pokeapi/client_mock.go -package=mockpokeapi
//

// Package mockpokeapi is a generated GoMock package.
package mockpokeapi

import (
	context "context"
	pokeapi "pokemon-cache-service/internal/pokeapi"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetPokemon mocks base method.
func (m *MockClient) GetPokemon(ctx context.Context, name string) (*pokeapi.PokemonData, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPokemon", ctx, name)
	ret0, _ := ret[0].(*pokeapi.PokemonData)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPokemon indicates an expected call of GetPokemon.
func (mr *MockClientMockRecorder) GetPokemon(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPokemon", reflect.TypeOf((*MockClient)(nil).GetPokemon), ctx, name)
}
